### ISSUE TITLE
cannot import name 'download_url' from 'pods.util'

### ISSUE THREAD

**Issue by tias** [lawrennd/cmtutils#1]
Curious to try out cmtutils for some analysis of a conference. Is it supposed to still work?

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a9f78b3c518b> in <module>
----> 1 import cmtutils.cmtutils as cu

~/.local/lib/python3.9/site-packages/cmtutils/__init__.py in <module>
----> 1 from .cmtutils import *
      2 from . import nipsy
      3 from . import plot

~/.local/lib/python3.9/site-packages/cmtutils/cmtutils.py in <module>
     16 from IPython.display import HTML
     17 
---> 18 from pods.util import download_url
     19 
     20 def display_url(target):

ImportError: cannot import name 'download_url' from 'pods.util' (/home/tias/.local/lib/python3.9/site-packages/pods/util.py)
```

**Comment by tias** [comment]
Just noted it was fixed in main, but that the version on pip does not yet have the fix.

Please release as a new version on pip.

For everybody else:
```
pip install git+https://github.com/lawrennd/cmtutils@main
```

**Comment by lawrennd** [comment]
Thanks for spotting Tias, I'll put out the new version on pip.

Let me know how you get along with it, it was built while programme chairing, so it's quite tailored for old version of CMT and held together by gaffer tape.

**Comment by lawrennd** [comment]
Should be there now! Tagged as version 0.1.2.

**Comment by tias** [comment]
OK, thanks for the quick response. I'm chairing ECMLPKDD and was hoping this could save me some file-parsing and wrangling... still have to find my way around though.

I can let you know later if it was helpful : )

BTW, see other issue on 'googoal' dependency
